Repository AY2425S2-CS2103T-W09-3/tp, pull requests merged in 2025-03, with the labels that each got.

#11 Update AboutUs.md
  docs/AboutUs.md
  docs/team/lekang.md
Labels: type.Task, priority.High

#40 Change Codecov configuration
  .github/workflows/gradle.yml
Labels: priority.Low

#43 Make PersonCard more descriptive
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
Labels: priority.Low

#51 Fix remark bug
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
Labels: type.Bug

#55 List limit command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/logic/parser/MedLoggerParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/MedLoggerParserTest.java
Labels: priority.Medium

#61 Export command
  docs/UserGuide.md
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/parser/ExportCommandParser.java
  src/main/java/seedu/address/logic/parser/MedLoggerParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/commons/util/FileUtilTest.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/parser/ExportCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MedLoggerParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: priority.Medium
